### ISSUE TITLE
Input axis is not set up (but it appears to be set up)

### ISSUE THREAD

**Issue by ghost** [DemoProductions/fighter#20]
Getting this error on play although the names of the inputs on my inputaxis appear to be correct. This is from develop

![inputaxis](https://cloud.githubusercontent.com/assets/10818718/10827970/0d66aa5c-7e2f-11e5-9999-4a4266b2d765.png)

Line 109 the error message is referencing gets input from the horizontal axes

Both players are still able to move but their hitboxes don't seem to be working for some reason (their hitbox is attached to PlayerMovement)

**Comment by flip40** [comment]
Click "Sanji" (the game object on the left) and then disable him (the highest checkbox in the inspector on the right). He is giving this error because he is not created by PlayerSpawner and thus has string inputs that are either empty string or null because they were never assigned.

See if hitboxes work after that, not sure why they are affected but I noticed some oddities with player control when the "test sanji" was not disabled and giving me this error as well.

We will eventually remove that "test sanji", but he is there so you can better see and modify his prefab (if you click just the prefab, for example, you can't see the HitBox child).

**Comment by ghost** [comment]
Works fine now. Thanks! Weird how the hitboxes stopped working

**Comment by flip40** [comment]
Awesome. I do agree it is weird, but at least we don't have to really worry about why that happens since we won't be including that test Sanji in the game.

By the way, if you think you will be making a PR for this today or tomorrow I think you should go ahead and add this testscene.unity and the Sanji.prefab to your commit. I believe you will be making changes to both of those for your healthbar stuff, and I don't think I will be making changes to those for a few days (either that or I can wait).

It would at least make it so test Sanji is disabled by default in the develop testscene and get your changes in there as well.

If you aren't sure you can always just wait on that until you are ready to PR and then we can decide if we should add those to overwrite the develop ones or just save them as separate scene and prefab files like we discussed in class on Wednesday. It is never too late to add those to your commit, but once you commit those files you are... "committed". Not sure if terrible pun.

**Comment by flip40** [comment]
Closing, this question and implied bug fix was fixed a few merges ago.
