### ISSUE TITLE
Using a joystick or controller

### ISSUE THREAD

**Issue by ghost** [DemoProductions/fighter#32]
Was using an xbox controller to move the player around but the animations tend to get stuck in a run animation since the xvelocity takes a little while to get to 0. Would need to add some delta value to see when the xvelocity is close enough to 0 for the player to be idle. 

Attached a snippet of a player's xvelocity after moving left on the joystick and then releasing the joystick to go back to neutral (this is over a few seconds)

[moveLeftJoystick.txt](https://github.com/DemoProductions/fighter/files/25071/moveLeftJoystick.txt)

**Comment by flip40** [comment]
Hm. I wonder what effect the dead value has on this. Was the player actually getting movement when it should not have (i.e. dead value too small)? Or was the player not moving with the proper dead range but this still reads as a non-0 input? If the latter, we should see if we can find a way to tie in to the dead value so that we don't have odd cases of "player moving but no animation" or "player animating but not moving" near the dead zone.

I really need to buy a wired controller for these kind of things :/

**Comment by ghost** [comment]
Oh so I just played around with the dead value and I didn't know it works just like adding a delta value to the xvelocity. A dead value of about 0.1 seems good. Feels like we should have a walk animation if we use joysticks though since we can vary the xvelocity more. 

I have a wireless adapter for xbox controllers and can bring it to class tomorrow along with a controller.

**Comment by ghost** [comment]
So earlier the player was getting movement when it should not have

**Comment by flip40** [comment]
Oh cool, glad the dead value works for that, makes our lives a bit easier. I agree we should get a walk animation for controllers though. I wonder if we can modify the speed of the animation based on imput somehow? With the variable speed it might make the animation look nicer if it speeds up to keep with the pace.

I was thinking adding controllers would be fun, we could get up to 4 players that way. Probably not something we should be too concerned with until the next project (not to say we can't work on it sooner if we have time). I'll add an enhancement issue for it.

**Comment by stannardtyler** [comment]
Adding a wall animation would be sweet for future animations!
